import logging
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session
from backend.app.core.database import get_db, WorldEvent, Opportunity, Risk
from backend.app.services.world_model.service import WorldModelService

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/world-model", tags=["World Model Engine"])

class IngestRequest(BaseModel):
    feed_urls: list[str] | None = None

class IngestResponse(BaseModel):
    status: str
    events_ingested: int
    alerts_triggered: list[dict]

class AlertItem(BaseModel):
    type: str
    id: str
    title: str
    detail: str | None = None
    metric: float | str | None = None

class WorldEventItem(BaseModel):
    id: str
    title: str
    category: str
    source_url: str | None = None
    relevance_score: float | None = None
    created_at: str

@router.post("/ingest", response_model=IngestResponse)
def trigger_ingest(payload: IngestRequest, db: Session = Depends(get_db)):
    """
    Triggers WME scraping cycles over tech feeds, computes relevance and registers new alerts.
    """
    logger.info("API trigger_ingest invoked.")
    try:
        res = WorldModelService.ingest_feeds(db, payload.feed_urls)
        return res
    except Exception as e:
        logger.error(f"Error during API feed ingestion: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Ingestion failed: {str(e)}")

@router.get("/alerts", response_model=list[AlertItem])
def get_active_alerts(db: Session = Depends(get_db)):
    """
    Retrieves all active Risks and Opportunities generated by the WME.
    """
    logger.info("API get_active_alerts invoked.")
    try:
        alerts = []
        
        # 1. Query WME Opportunities
        opps = db.query(Opportunity).filter(Opportunity.title.like("Emerging Tech Opportunity:%")).all()
        for o in opps:
            alerts.append(AlertItem(
                type="opportunity",
                id=str(o.id),
                title=o.title,
                detail=o.description,
                metric=o.relevance_score
            ))
            
        # 2. Query WME Risks
        risks = db.query(Risk).filter(Risk.title.like("Security Advisory:%")).all()
        for r in risks:
            alerts.append(AlertItem(
                type="risk",
                id=str(r.id),
                title=r.title,
                detail=r.description,
                metric=r.severity
            ))
            
        return alerts
    except Exception as e:
        logger.error(f"Error getting WME alerts: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to fetch alerts: {str(e)}")

@router.get("/events", response_model=list[WorldEventItem])
def get_world_events(db: Session = Depends(get_db)):
    """
    Retrieves logged world events history.
    """
    logger.info("API get_world_events invoked.")
    try:
        events = db.query(WorldEvent).order_by(WorldEvent.created_at.desc()).all()
        result = []
        for e in events:
            relevance = e.event_payload.get("relevance_score") if e.event_payload else None
            result.append(WorldEventItem(
                id=str(e.id),
                title=e.title,
                category=e.category,
                source_url=e.source_url,
                relevance_score=relevance,
                created_at=e.created_at.isoformat()
            ))
        return result
    except Exception as e:
        logger.error(f"Error getting world events: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to fetch world events: {str(e)}")
